project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true

render:
  - "*.qmd"
  - "guia/*.qmd"
  - "contenido/*.qmd"

website:
  title: "Política del Lenguaje"
  site-url: https://politicadellenguaje.juanpaulo.xyz/course
  favicon: ../../images/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: evaluacion/index.qmd
        text: Evaluación
      - href: guia/index.qmd
        text: Guía para el profesor
      - href: references.qmd
        text: Bibliografía
      - href: about.qmd
        text: Sobre este curso

lang: es

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-after-body:
      - file: references-links.html
    toc: true
    toc-title: "En esta unidad"
    code-fold: false
    code-tools: true
    filters:
      - pyodide
